# Generated by Django 5.0 on 2024-02-02 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Painter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('about', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('age', models.IntegerField(null=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_picture/')),
                ('date_born', models.DateField(null=True)),
                ('group', models.ManyToManyField(related_name='painter', to='webapp.group')),
            ],
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('released_date', models.DateField(auto_now=True)),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('painter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.painter')),
            ],
        ),
        migrations.CreateModel(
            name='Sculptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('about', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('age', models.IntegerField(null=True)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_picture/')),
                ('date_born', models.DateField(null=True)),
                ('group', models.ManyToManyField(related_name='sculptor', to='webapp.group')),
            ],
        ),
        migrations.CreateModel(
            name='Sculpture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('released_date', models.DateField(auto_now=True)),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('sculptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.sculptor')),
            ],
        ),
    ]
